<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssociationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('associations')->delete();
        DB::table('associations')->insert([
            [
                'user_name' => 'Duytan123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'Duytan123@gmail.com',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '(+84) 236.3650403 ',
                'registered_phone_number' => '0987654321',
                'address' => '254 Nguyễn Văn Linh, Quận Thanh Khê, Tp. Đà Nẵng',
                'website' => 'https://duytan.edu.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/duy-tan-480x300.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Đại Học Duy Tân',
                'is_master' => 1,
            ],
            [
                'username' => 'Agility123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'hi@agilityio.com.vn',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => '604 Núi Thành, Phường Hoà Cường Nam, Quận Hải Châu, Đà Nẵng, Việt Nam',
                'website' => 'https://agilityio.com.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/10/AgilityIO-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty Agility',
                'is_master' => 0,
            ],
            [
                'username' => 'Asiantech123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@asiantech.vn',
                'registrant_name' => 'Trần Đoàn Đình Long',
                'subscriber_email' => 'Longtran@gmail.com',
                'phone_number' => '02363664579',
                'registered_phone_number' => '0987654321',
                'address' => 'Lô 35, Đường số 4, Khu công nghiệp Đà Nẵng, Quận Sơn Trà, Đà Nẵng, Việt Nam',
                'website' => 'https://asiantech.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/asiantech-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty TNHH Asian Tech',
                'is_master' => 0,
            ],
            [
                'username' => 'Axonactive123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'info@axonactive.com',
                'registrant_name' => 'Trần Đoàn Đình Long',
                'subscriber_email' => 'Longtran@gmail.com',
                'phone_number' => '(+84)(236)7109 123',
                'registered_phone_number' => '0987654321',
                'address' => 'Tầng 13 Tòa nhà PVcomBank, đường 30/4, Quận Hải Châu, Đà Nẵng, Việt Nam',
                'website' => 'https://www.axonactive.com',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/axon-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công Ty TNHH Axon Active Việt Nam',
                'is_master' => 0,
            ],
            [
                'username' => 'Cnttdn123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'iid@danang.gov.vn',
                'registrant_name' => 'Trần Đoàn Đình Long',
                'subscriber_email' => 'Longtran@gmail.com',
                'phone_number' => '(+84) 236.3 888 414',
                'registered_phone_number' => '0987654321',
                'address' => 'Tòa nhà 02 Quang Trung, Phường Thạch Thang, Quận Hải Châu, Tp Đà Nẵng',
                'website' => 'https://dsp.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/DSP-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Trung tâm Phát triển hạ tầng CNTT Đà Nẵng',
                'is_master' => 0,
            ],
            [
                'username' => 'Cntttt123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'dnict@danang.gov.vn',
                'registrant_name' => 'Trần Đoàn Đình Long',
                'subscriber_email' => 'Longtran@gmail.com',
                'phone_number' => '(+84) 236.3 888 414',
                'registered_phone_number' => '0987654321',
                'address' => '15 Quang Trung , Phường Hải Châu 1,Quận Hải Châu,TP. Đà Nẵng',
                'website' => 'https://dnict.vn/',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/DNICT-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Trung tâm Công nghệ Thông tin và Truyền thông Đà Nẵng',
                'is_master' => 0,
            ],
            [
                'username' => 'Cndtttt@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@dtt.vn',
                'registrant_name' => 'Trần Đoàn Đình Long',
                'subscriber_email' => 'Longtran@gmail.com',
                'phone_number' => '(+84) 236.3 888 414',
                'registered_phone_number' => '0987654321',
                'address' => '213 Nguyễn Tất Thành, Thanh Bình, Hải Châu, Đà Nẵng',
                'website' => 'https://dtt.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/DTT-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công Ty Cổ Phần Công Nghệ DTT',
                'is_master' => 0,
            ],
            [
                'username' => 'Cndtt@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@dtt.vn',
                'registrant_name' => 'Trần Đoàn Đình Long',
                'subscriber_email' => 'Longtran@gmail.com',
                'phone_number' => '(+84) 236.3 888 414',
                'registered_phone_number' => '0987654321',
                'address' => '213 Nguyễn Tất Thành, Thanh Bình, Hải Châu, Đà Nẵng',
                'website' => 'https://dtt.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/DTT-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công Ty Cổ Phần Công Nghệ DTT',
                'is_master' => 0,
            ],
            [
                'username' => 'Fpt@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'fsoft.contact@fsoft.com.vn',
                'registrant_name' => 'Trần Đoàn Đình Long',
                'subscriber_email' => 'Longtran@gmail.com',
                'phone_number' => '(+84) 236.3 888 414',
                'registered_phone_number' => '0987654321',
                'address' => 'FPT Complex, đường Nam Kỳ Khởi Nghĩa, phường Hoà Hải, quận Ngũ Hành Sơn, Đà Nẵng, Việt Nam',
                'website' => 'https://fpt-software.com',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/fpt-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty TNHH FPT Software',
                'is_master' => 0,
            ],
            [
                'username' => 'Cyber123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'salesvn@gcs-vn.com',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => 'Tầng 5, Tòa nhà VNPT, 346 , 2/9, Phườnường Bắc, Quận Hải Châu, Thành phố Đà Nẵng, Việt Nam',
                'website' => 'https://globalcybersoft.com',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/cybersoft-12-480x300.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Chi Nhánh Công Ty Cổ Phần Global CYBERSOFT (Việt Nam)',
                'is_master' => 0,
            ],
            [
                'username' => 'Cnttxanh123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@greenglobal.vn',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => '31 Trần Phú, Phường Hải Châu 1, Quận Hải Châu, Đà Nẵng',
                'website' => 'https://greenglobal.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/green_global-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty tư vấn giải pháp công nghệ thông tin Toàn Cầu Xanh',
                'is_master' => 0,
            ],
            [
                'username' => 'Thuongmai123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'support@htk-inc.com',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => '57 Tôn Thất Đạm, Quận Thanh Khê, Thành phố Đà Nẵng, Việt Nam',
                'website' => 'https://htk-inc.com',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/HTK-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty TNHH thương mại và dịch vụ công nghệ H.T.K  I.N.C',
                'is_master' => 0,
            ],
            [
                'username' => 'Iviet123@gmail.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@iviettech.vn',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => '92 Quang Trung, Q. Hải Châu, TP. Đà Nẵng',
                'website' => 'https://iviettech.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/09/iviettech2.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Trung tâm đào tạo Lập trình viên chuyên nghiệp iVietTech',
                'is_master' => 0,
            ],
            [
                'username' => 'contact@rikkeisoft.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@rikkeisoft.com',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => 'Tầng 11 Tòa nhà VietNam News Agency, 81 Quang Trung, Quận Hải Châu, Đà Nẵng, Việt Nam',
                'website' => 'www.rikkeisoft.com',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2020/06/Logo-Rikkei.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty TNHH Rikkeisoft',
                'is_master' => 0,
            ],
            [
                'username' => 'info@tinhvan.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'info@tinhvan.com',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => '115 Nguyễn Văn Linh, Phường Nam Dương, Đà Nẵng',
                'website' => 'https://viethanit.edu.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2018/01/Tinh-Van-300x200.jpg',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty Cổ phần Xuất khẩu Phần mềm Tinh Vân',
                'is_master' => 0,
            ],
            [
                'username' => 'contact@unitech.vn',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@unitech.vn',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => 'Tầng 07 Công viên phần mềm Đà Nẵng  Số 02 Quang Trung, TP Đà Nẵng',
                'website' => 'www.unitech.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/unitech-480x300.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty Cổ phần Unitech',
                'is_master' => 0,
            ],
            [
                'username' => 'van.banh@logigear.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'van.banh@logigear.com',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => '346, 2 Tháng 9, Hải Châu, Đà Nẵng',
                'website' => 'https://www.logigear.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/11/gear-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty TNHH Logigear Việt Nam',
                'is_master' => 0,
            ],
            [
                'username' => 'info@magrabbit.com',
                'password' => bcrypt('12345678'),
                'company_email' => 'info@magrabbit.com',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => 'Số 2 Đường Quang Trung Đà Nẵng, Việt Nam',
                'website' => 'https://magrabbit.com',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2017/09/MagRabbit_Logo_2-300x200.png',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'CÔNG TY TNHH MAGRABBIT VIỆT NAM',
                'is_master' => 0,
            ],
            [
                'username' => 'contact@nal.vn',
                'password' => bcrypt('12345678'),
                'company_email' => 'contact@nal.vn',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => 'Phòng 501, 02 Quang Trung, Đà Nẵng',
                'website' => 'https://nal.vn',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2018/01/Nal-Solution-300x200.jpg',

                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty Nal Solutions',
                'is_master' => 0,
            ],
            [
                'username' => 'info@novaio.vn',
                'password' => bcrypt('12345678'),
                'company_email' => 'info@novaio.vn',
                'registrant_name' => 'Huỳnh Lê Quang Huy',
                'subscriber_email' => 'Huy281002@gmail.com',
                'phone_number' => '02363797990',
                'registered_phone_number' => '0987654321',
                'address' => 'Tầng 10, 02 Quang Trung, Hải Châu, Đà Nẵng',
                'website' => 'https://www.novaio.vn/',
                'avatar' => 'https://dsa.org.vn/wp-content/uploads/2018/03/novaio-logo-b.png',
                'is_active' => 1,
                'is_open' => 1,
                'company_name' => 'Công ty cổ phần công nghệ Novaio',
                'is_master' => 0,
            ],
        ]);
    }
}
